<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Jagseer" ignored="0" name="TitleValidation" tests="2" failures="2" timestamp="14 Jun 2020 06:08:51 GMT" time="13.318" errors="0">
  <testcase name="First" time="0.008" classname="Practical.RealProject.ValidationTitles">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at java.io.File.<init>(Unknown Source)
at com.aventstack.extentreports.reporter.BasicFileReporter.<init>(BasicFileReporter.java:67)
at com.aventstack.extentreports.reporter.ExtentSparkReporter.<init>(ExtentSparkReporter.java:35)
at Practical.RealProject.Reports.Repo(Reports.java:12)
at Practical.RealProject.Listeners.onTestStart(Listeners.java:19)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- First -->
  <testcase name="First" time="1.02" classname="Practical.RealProject.ValidationTitles">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at Practical.RealProject.Listeners.onTestFailure(Listeners.java:57)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- First -->
</testsuite> <!-- TitleValidation -->
